name: Deploy to GitHub Pages

on:
  # Activa el robot cada vez que subas código a la rama principal (main)
  push:
    branches: [ main ]
  # Permite correr este proceso manualmente si es necesario
  workflow_dispatch:

# Permisos que necesita el robot para subir los archivos
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v3

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4